version: "3.2"

volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.111.111,soft,nolock,rw
      device: :/mnt/data/media

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - media:/media
      - /docker/audiobookshelf/config:/config
      - /docker/audiobookshelf/metadata:/metadata
    environment:
      - TZ=Australia/Melbourne
      - PUID=1000
      - PGID=1000
    restart: unless-stopped