version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /portainer/apps/bazarr/config:/config
      - /portainer/Movies:/movies
      - /portainer/TV:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
