version: "3.2"

volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.111.111,soft,nolock,rw
      device: :/mnt/data/media
      
services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Australia/Melbourne
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - /docker/qbittorrent:/config
      - media:/media