version: "3.2"

volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.111.111,soft,nolock,rw
      device: :/mnt/data/media

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    network_mode: 'host'
    volumes:
      - /docker/jellyfin/confg:/config
      - /docker/jellyfin/cache:/cache
      - media:/media
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
    restart: 'unless-stopped'