version: "3.2"

volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.111.111,soft,nolock,rw
      device: :/mnt/data/media/comics

services:
    kapowarr:
        container_name: kapowarr
        volumes:
            - /docker/kapowarr:/app/db'
            - media:/media
        ports:
            - '5656:5656'
        image: 'mrcas/kapowarr:latest'