version: "3.2"

volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.111.111,soft,nolock,rw
      device: :/mnt/data/media

services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - /docker/komga:/config
      - media:/media
    ports:
      - 25600:25600
    user: "1000:1000"
    restart: unless-stopped