version: '3'

services:
    maintainerr:
        image: ghcr.io/jorenn92/maintainerr:latest
        container_name: maintainerr
        user: 1000:1000
        volumes:
          - /docker/maintainerr:/opt/data
        environment:
          - PGID=1000
          - PUID=1000
          - TZ=Australia/Melbourne
#      - DEBUG=true # uncomment to enable debug logs
        ports:
          - 6246:6246
        restart: unless-stopped