version: "3.2"

volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.111.111,soft,nolock,rw
      device: :/mnt/data/media

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /docker/radarr:/config
      - media:/mediae
    ports:
      - 7878:7878
    restart: unless-stopped